name: Deploiement

on:
  push:
    branches: [ master ]

jobs:
  versionpatch:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[PATCH]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name '${{ secrets.GH_PUBLIC_NAME }}'
      - run: git config --global user.email '${{ secrets.GH_EMAIL }}'
      - run: npm version patch -m "[VERSION PATCH] %s"
      - run: git push
      - run: git tag
      - run: git push --tags
  versionminor:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[MINOR]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name '${{ secrets.GH_PUBLIC_NAME }}'
      - run: git config --global user.email '${{ secrets.GH_EMAIL }}'
      - run: npm version minor -m "[VERSION MINOR] %s"
      - run: git push
      - run: git tag
      - run: git push --tags                                
  publish:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[VERSION')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[VERSION')"
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run build-storybook
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        local-dir: "storybook-static/"
        server-dir: "public_html/storybook/"
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWOR}}
